# Generated by Django 3.2 on 2021-05-07 22:37

from django.db import migrations
import stories.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hidespot_x',
            field=stories.fields.XField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='story',
            name='hidespot_y',
            field=stories.fields.YField(default=0, editable=False),
        ),
    ]
